services:
  frontend:
    # La imagen será descargada del registro de GitHub (GHCR)
    image: ghcr.io/${GITHUB_REPOSITORY}-frontend:latest
    container_name: plapi_frontend
    restart: always
    ports:
      - "8050:80" # El frontend se sirve en el puerto estándar web
    depends_on:
      - backend
    networks:
      - plapi-network

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}-backend:latest
    container_name: plapi_backend
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - plapi-network

  mysql:
    image: mysql:8.0
    container_name: plapi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - plapi-mysql-data-prod:/var/lib/mysql
    networks:
      - plapi-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: plapi_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - plapi-network

networks:
  plapi-network:
    driver: bridge

volumes:
  plapi-mysql-data-prod:
