FROM node:20-alpine

WORKDIR /usr/src/app

# Instala dependencias
COPY package*.json ./
RUN npm install

# Copia el código
COPY . .

# Expone el puerto por defecto del backend
EXPOSE 3000

# El comando de inicio está en docker-compose.yml