FROM node:20-alpine

WORKDIR /app

# Instala dependencias
COPY package*.json ./
RUN npm install

# Copia el código
COPY . .

# Expone el puerto por defecto de Vite
EXPOSE 5173

# El comando de inicio está en docker-compose.yml